// <auto-generated />
using System;
using ArcelorMittal.UnifiedWeightSystem.Common.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArcelorMittal.UnifiedWeightSystem.Common.Migrations
{
    [DbContext(typeof(UwsDbContext))]
    [Migration("20200520074203_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("LastStageId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("WeightCollectionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LastStageId")
                        .IsUnique()
                        .HasFilter("[LastStageId] IS NOT NULL");

                    b.HasIndex("WeightCollectionId");

                    b.ToTable("StageHistory");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Log.UwsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecognCollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UwsLogDetailId")
                        .HasColumnType("bigint");

                    b.Property<int?>("UwsLogTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("WeightCollectionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UwsLogDetailId");

                    b.HasIndex("UwsLogTypeId");

                    b.HasIndex("WeightCollectionId");

                    b.ToTable("UwsLogs");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Log.UwsLogDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UwsLogDetails");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Log.UwsLogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UwsLogTypes");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Direction")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("DtBegin")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DtEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("LocalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Release")
                        .HasColumnType("bit");

                    b.Property<int?>("ScalesSerial")
                        .HasColumnType("int");

                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint");

                    b.Property<string>("TrainStatus")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("WeightCollections");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightCollectionProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<long>("WeightCollectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("WeightPropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightCollectionId");

                    b.HasIndex("WeightPropertyTypeId");

                    b.ToTable("WeightCollectionProperties");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AxisCount")
                        .HasColumnType("int");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<byte?>("OrderNumber")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Quality")
                        .HasColumnType("tinyint");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("TypeWeight")
                        .HasColumnType("tinyint");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<long?>("WeightCollectionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WeightCollectionId");

                    b.ToTable("WeightElements");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElementProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<long>("WeightElementId")
                        .HasColumnType("bigint");

                    b.Property<int>("WeightPropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightElementId");

                    b.HasIndex("WeightPropertyTypeId");

                    b.ToTable("WeightElementProperties");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightPropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("WeightPropertyTypes");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", "LastStage")
                        .WithOne()
                        .HasForeignKey("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", "LastStageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightCollection", "WeightCollection")
                        .WithMany()
                        .HasForeignKey("WeightCollectionId");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Log.UwsLog", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.Log.UwsLogDetail", "UwsLogDetail")
                        .WithMany()
                        .HasForeignKey("UwsLogDetailId");

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.Log.UwsLogType", "UwsLogType")
                        .WithMany()
                        .HasForeignKey("UwsLogTypeId");

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightCollection", "WeightCollection")
                        .WithMany()
                        .HasForeignKey("WeightCollectionId");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightCollectionProperty", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightCollection", "WeightCollection")
                        .WithMany()
                        .HasForeignKey("WeightCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightPropertyType", "WeightPropertyType")
                        .WithMany()
                        .HasForeignKey("WeightPropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElement", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightCollection", "WeightCollection")
                        .WithMany("WeightElements")
                        .HasForeignKey("WeightCollectionId")
                        .HasConstraintName("FK_ShipmentId_Shipments");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElementProperty", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElement", "WeightElement")
                        .WithMany()
                        .HasForeignKey("WeightElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightPropertyType", "WeightPropertyType")
                        .WithMany()
                        .HasForeignKey("WeightPropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
