// <auto-generated />
using System;
using ArcelorMittal.UnifiedWeightSystem.Common.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArcelorMittal.UnifiedWeightSystem.Common.Migrations
{
    [DbContext(typeof(UwsDbContext))]
    [Migration("20200604102507_AddStatusColor")]
    partial class AddStatusColor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.DiagnosticProcess.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessCellId")
                        .HasColumnType("int");

                    b.Property<bool>("StatusColor")
                        .HasColumnType("bit");

                    b.Property<int?>("StatusTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.DiagnosticProcess.StatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Default")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("StatusTypes");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.DiagnosticProcess.UwsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Callsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessCellId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("UwsLog");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LastStageId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<int?>("WeightingCollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastStageId")
                        .IsUnique()
                        .HasFilter("[LastStageId] IS NOT NULL");

                    b.HasIndex("WeightingCollectionId");

                    b.ToTable("StageHistory");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DtBegin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DtEnd")
                        .HasColumnType("datetime");

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.Property<bool?>("Release")
                        .HasColumnType("bit");

                    b.Property<int?>("ScalesSerial")
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("WeightingCollections");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollectionProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("WeightingCollectionId")
                        .HasColumnType("int");

                    b.Property<int>("WeightingPropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightingCollectionId");

                    b.HasIndex("WeightingPropertyTypeId");

                    b.ToTable("WeightingCollectionProperties");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AxisCount")
                        .HasColumnType("int");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<string>("RecNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<int>("TypeWeight")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int?>("WeightingCollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("WeightingOperationsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightingCollectionId");

                    b.ToTable("WeightingElements");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingElementProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("WeightElementId")
                        .HasColumnType("int");

                    b.Property<int>("WeightingPropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightElementId");

                    b.HasIndex("WeightingPropertyTypeId");

                    b.ToTable("WeightingElementProperties");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingPropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("WeightingPropertyTypes");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.DiagnosticProcess.Status", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.DiagnosticProcess.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", "LastStage")
                        .WithOne()
                        .HasForeignKey("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", "LastStageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", "WeightingCollection")
                        .WithMany()
                        .HasForeignKey("WeightingCollectionId");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollectionProperty", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", "WeightingCollection")
                        .WithMany()
                        .HasForeignKey("WeightingCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingPropertyType", "WeightingPropertyType")
                        .WithMany()
                        .HasForeignKey("WeightingPropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingElement", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", "WeightingCollection")
                        .WithMany("WeightingElements")
                        .HasForeignKey("WeightingCollectionId")
                        .HasConstraintName("FK_ShipmentId_Shipments");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingElementProperty", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingElement", "WeightElement")
                        .WithMany()
                        .HasForeignKey("WeightElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingPropertyType", "WeightingPropertyType")
                        .WithMany()
                        .HasForeignKey("WeightingPropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
