// <auto-generated />
using System;
using ArcelorMittal.UnifiedWeightSystem.Common.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArcelorMittal.UnifiedWeightSystem.Common.Migrations
{
    [DbContext(typeof(UwsDbContext))]
    [Migration("20200520195512_UpdateWeightCollection")]
    partial class UpdateWeightCollection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LastStageId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WeightingCollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastStageId")
                        .IsUnique()
                        .HasFilter("[LastStageId] IS NOT NULL");

                    b.HasIndex("WeightingCollectionId");

                    b.ToTable("StageHistory");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Logging.UwsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecognCollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UwsLogDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("UwsLogTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("WeightingCollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UwsLogDetailId");

                    b.HasIndex("UwsLogTypeId");

                    b.HasIndex("WeightingCollectionId");

                    b.ToTable("UwsLogs");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Logging.UwsLogDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UwsLogDetails");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Logging.UwsLogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UwsLogTypes");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AxisCount")
                        .HasColumnType("int");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<string>("RecNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TypeWeight")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<int?>("WeightingCollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("WeightingOperationsID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightingCollectionId");

                    b.ToTable("WeightElements");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElementProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("WeightElementId")
                        .HasColumnType("int");

                    b.Property<int>("WeightPropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightElementId");

                    b.HasIndex("WeightPropertyTypeId");

                    b.ToTable("WeightElementProperties");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightPropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("WeightPropertyTypes");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DtBegin")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DtEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.Property<bool>("Release")
                        .HasColumnType("bit");

                    b.Property<int?>("ScalesSerial")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("TrainStatus")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("WeightingCollections");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollectionProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("WeightPropertyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WeightingCollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightPropertyTypeId");

                    b.HasIndex("WeightingCollectionId");

                    b.ToTable("WeightingCollectionProperties");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", "LastStage")
                        .WithOne()
                        .HasForeignKey("ArcelorMittal.UnifiedWeightSystem.Common.Documentation.StageHistory", "LastStageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", "WeightingCollection")
                        .WithMany()
                        .HasForeignKey("WeightingCollectionId");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.Logging.UwsLog", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.Logging.UwsLogDetail", "UwsLogDetail")
                        .WithMany()
                        .HasForeignKey("UwsLogDetailId");

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.Logging.UwsLogType", "UwsLogType")
                        .WithMany()
                        .HasForeignKey("UwsLogTypeId");

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", "WeightingCollection")
                        .WithMany()
                        .HasForeignKey("WeightingCollectionId");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElement", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", "WeightingCollection")
                        .WithMany("WeightElements")
                        .HasForeignKey("WeightingCollectionId")
                        .HasConstraintName("FK_ShipmentId_Shipments");
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElementProperty", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightElement", "WeightElement")
                        .WithMany()
                        .HasForeignKey("WeightElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightPropertyType", "WeightPropertyType")
                        .WithMany()
                        .HasForeignKey("WeightPropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollectionProperty", b =>
                {
                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightPropertyType", "WeightPropertyType")
                        .WithMany()
                        .HasForeignKey("WeightPropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcelorMittal.UnifiedWeightSystem.Common.WeightingProcess.WeightingCollection", "WeightingCollection")
                        .WithMany()
                        .HasForeignKey("WeightingCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
